apiVersion: v1
kind: Service
metadata:
  name: aianalysis-service
  labels:
    app: aianalysis-app
spec:
  type: NodePort
  selector:
    app: aianalysis-app
  ports:
    - name: http
      nodePort: 30002
      port: 9091
      targetPort: 9091
      protocol: TCP